<a href="https://colab.research.google.com/github/ASWATHI-A123/ASWATHI-A/blob/main/Assignment_on_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
data=pd.read_excel('/content/iris (2).xls')

In [52]:
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              143 non-null    float64
 1   SW              144 non-null    float64
 2   PL              144 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [54]:
data.shape

(150, 5)

In [55]:
data.value_counts()

SL   SW   PL   PW   Classification 
4.9  3.1  1.5  0.1  Iris-setosa        3
5.8  2.7  5.1  1.9  Iris-virginica     2
6.3  2.9  5.6  1.8  Iris-virginica     1
6.2  2.9  4.3  1.3  Iris-versicolor    1
     3.4  5.4  2.3  Iris-virginica     1
                                      ..
5.4  3.9  1.3  0.4  Iris-setosa        1
     3.4  1.7  0.2  Iris-setosa        1
          1.5  0.4  Iris-setosa        1
     3.0  4.5  1.5  Iris-versicolor    1
7.9  3.8  6.4  2.0  Iris-virginica     1
Length: 128, dtype: int64

In [56]:
data.isna().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

In [57]:
feature_with_na=[features for features in data.columns if data[features].isna().sum()>0]

In [58]:
feature_with_na

['SL', 'SW', 'PL']

In [59]:
for feature in feature_with_na:
  print(feature,np.round(data[feature].isnull().mean(),2))

SL 0.05
SW 0.04
PL 0.04


In [60]:
data['SL'].fillna(data['SL'].mean(), inplace=True)

In [61]:
data['SW'].fillna(data['SW'].mean(), inplace=True)

In [62]:
data['PL'].fillna(data['PL'].mean(), inplace=True)

In [63]:
data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [64]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Classification']=le.fit_transform(data['Classification'])

In [65]:
data

SL   SW       PL   PW  Classification
0    5.100000  3.5  1.40000  0.2               0
1    4.900000  3.0  1.40000  0.2               0
2    5.855944  3.2  1.30000  0.2               0
3    4.600000  3.1  1.50000  0.2               0
4    5.000000  3.6  1.40000  0.2               0
..        ...  ...      ...  ...             ...
145  6.700000  3.0  5.20000  2.3               2
146  6.300000  2.5  5.00000  1.9               2
147  6.500000  3.0  3.75625  2.0               2
148  6.200000  3.4  5.40000  2.3               2
149  5.900000  3.0  5.10000  1.8               2

[150 rows x 5 columns]

In [66]:
x=data.drop(['SL','SW','PL','PW'],axis=1)
y=data['Classification']

**LOGISTIC REGRESSION**

In [67]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [68]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
model=lr.fit(x_train,y_train)

In [69]:
y_predictions=model.predict(x_test)

In [70]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [71]:
confusion_matrix(y_test,y_predictions)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [72]:
print('Accuracy=',accuracy_score(y_test,y_predictions))

Accuracy= 1.0


### **SVM**

In [73]:
from sklearn.svm import SVC
svmclf=SVC(kernel='linear')
svmclf.fit(x_train,y_train)

SVC(kernel='linear')

In [74]:
y_pred=svmclf.predict(x_test)

In [75]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('Accuracy is',accuracy_score(y_test,y_pred))

Accuracy is 1.0


In [76]:
print(confusion_matrix(y_test,y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


**DECISION TREE**

In [77]:
from sklearn.tree import DecisionTreeClassifier
dt_clf=DecisionTreeClassifier()
dt_clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [78]:
y_pred=dt_clf.predict(x_test)

In [79]:
print('Accuracy is',accuracy_score(y_test,y_pred))

Accuracy is 1.0


In [80]:
print(confusion_matrix(y_test,y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


**RANDOM FOREST**

In [81]:
from sklearn.ensemble import RandomForestClassifier
rf_clf=RandomForestClassifier()
rf_clf.fit(x_train,y_train)

RandomForestClassifier()

In [82]:
y_pred=rf_clf.predict(x_test)

In [83]:
print('Accuracy is :',accuracy_score(y_test,y_pred))

Accuracy is : 1.0
